name: stonks
description: tracking US stocks and cryptocurrencies

publish_to: "none" 

version: 2.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  intl: ^0.17.0
  provider: ^6.0.2
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.1.5
  internet_connection_checker: ^0.0.1+3
  syncfusion_flutter_charts: ^20.2.49

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  lints: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png